application: mmsifang
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: /static/
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /(crawl|start)
  script: controller.py
