application: ajaxkernel
version: 1
runtime: python
api_version: 1

builtins:
- admin_redirect: on
- datastore_admin: on
- remote_api: on
- deferred: on

handlers:
- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

#- url: /_ah/queue/deferred
#  script: djangoappengine/deferred/handler.py
#  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media
  static_dir: media/
  expiration: '365d'

- url: /_service/.*
  script: _service.py
  login: admin

- url: /.*
  script: djangoappengine/main/main.py
