application: disk-balancer
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: controller.py
- url: /upload
  script: controller.py
- url: /dl.*
  script: controller.py
- url: /notify
  script: controller.py
- url: /status
  script: controller.py
- url: /admin.*
  script: admin.py
  login: admin
- url: .*
  script: controller.py
