application: wppush
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static
  static_dir: static
- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
